
authToken.header=Authorization

#JWT authentication configuration for sm-shop
jwt.header=Authorization
jwt.secret=YVNlY3JldEtleVRoYXRJc0F0TGVhc3Q2NEJ5dGVzTG9uZ0ZvckhTNTEyU2lnbmluZ0FsZ29yaXRobVJlcXVpcmVtZW50cw==
jwt.expiration= 604800


#Your facebook app informations
facebook.app.id=
facebook.app.secret=
facebook.app.access_token=








